SERVICE_DOMAIN_MAP = {
    "google": "google.com",
    "youtube": "youtube.com",
    "vk": "vk.com",
    "github": "github.com",
    "mail": "mail.ru",
    "yandex": "yandex.ru",
    "facebook": "facebook.com",
    "instagram": "instagram.com",
    "twitter": "twitter.com",
    "telegram": "telegram.org",
    "steam": "steamcommunity.com",
    "discord": "discord.com",
    "twitch": "twitch.tv",
    "tiktok": "tiktok.com",
    "reddit": "reddit.com",
    "pinterest": "pinterest.com",
    "linkedin": "linkedin.com",
    "spotify": "spotify.com",
    "apple": "apple.com",
    "amazon": "amazon.com",
    "aliexpress": "aliexpress.com",
    "netflix": "netflix.com",
    "microsoft": "microsoft.com",
    "whatsapp": "whatsapp.com",
    "zoom": "zoom.us",
    "skype": "skype.com",
    "ebay": "ebay.com",
    "paypal": "paypal.com",
    "ok": "ok.ru",
    "wildberries": "wildberries.ru",
    "ozon": "ozon.ru"
    
}